# Generated by Django 3.2.7 on 2021-10-09 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.MinLengthValidator(3, 'Minimum Lenth should be 3')]),
            preserve_default=False,
        ),
    ]
